[]

nodaemon=true


[program:x-ui]

command=/opt/x-ui/x-ui

directory=/opt/x-ui

autostart=true

autorestart=true


[program:nginx]

command=/usr/sbin/nginx -g "daemon off;"

autostart=true

autorestart=true
